services:
  admin:
    build:
      dockerfile: Dockerfile
    image: app-admin
    container_name: app_admin
    working_dir: /app
    # volumes:
    #   - ./28movies.backend:/app
    ports:
      - "9000"
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
    networks:
      - app-network
  queue:
    image: app-admin
    container_name: admin_queue
    working_dir: /app
    command: php artisan queue:work --daemon --sleep=3 --tries=3 --timeout=60
    env_file:
      - .env
    depends_on:
      - admin
    restart: always
    networks:
      - app-network
networks:
  app-network:
    external: true
    name: app-network